### ISSUE TITLE
Incorrect documentation, how to do it correctly?

### ISSUE THREAD

**Issue by AlexeyRaga** [charlypoly/graphql-mesh-docs-first-gateway#31]
The documentation for [combining multiple sources](https://the-guild.dev/graphql/mesh/docs/getting-started/combine-multiple-sources) has this code:

```
  extend type Book {
    author: authors_v1_Author @resolveTo(
      sourceName: "Authors" # Which source does the target field belong to?
      sourceTypeName: "Query", # Which root type does the target field belong to?
      sourceFieldName: "authors_v1_AuthorsService_GetAuthor", # What is the source field name?
      requiredSelectionSet: "{ authorId }",
      sourceArgs: # What args does this need to take? {
        "input.id": "{root.authorId}"
      }
    )
  }
```

It has missing commas and misplaced comments, but even after fixing those I cannot figure out how to make it work.

I now have it as

```yaml
additionalTypeDefs: |
  extend type Book {
    author: authors_v1_Author @resolveTo(
      sourceName: "Authors",
      sourceTypeName: "Query",
      sourceFieldName: "authors_v1_AuthorsService_GetAuthor",
      requiredSelectionSet: "{ authorId }",
      sourceArgs: {
        "input.id": "{root.authorId}"
      }
    )
  }
```

And here is the error message that I get:

```
Mesh AggregateError: Failed to find any GraphQL type definitions in: extend type Book {
  author: authors_v1_Author @resolveTo(
    sourceName: "Authors",
    sourceTypeName: "Query",
    sourceFieldName: "authors_v1_AuthorsService_GetAuthor",
    requiredSelectionSet: "{ authorId }",
    sourceArgs: {
      "input.id": "{root.authorId}"
    }
  )
}
;
 - ENAMETOOLONG: name too long, stat '/service/extend type Book {
  author: authors_v1_Author @resolveTo(
    sourceName: "Authors",
    sourceTypeName: "Query",
    sourceFieldName: "authors_v1_AuthorsService_GetAuthor",
    requiredSelectionSet: "{ authorId }",
    sourceArgs: {
      "input.id": "{root.authorId}"
    }
  )
}
```

Using `additionalResolvers` in yaml works, but I still want to make it work in this more explicit way.

I am using the following versions of packages:

```json
  "dependencies": {
    "@graphql-mesh/cli": "^0.82.35",
    "@graphql-mesh/graphql": "^0.93.1",
    "@graphql-mesh/openapi": "^0.93.1",
    "@graphql-mesh/grpc": "^0.93.2",
    "@graphql-mesh/runtime": "^0.93.2",
    "@graphql-mesh/transform-filter-schema": "^0.93.2",
    "@graphql-mesh/transform-rename": "^0.93.1",
    "graphql": "^16.3.0"
  }
```

Can anyone please advise on how to make it work?
